<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Company>HeavyFeel</Company>
    <Product>HeavyFeel</Product>
    <Version>0.2.2</Version>
    <Authors>HeavyFeel</Authors>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <PlatformTarget>x64</PlatformTarget>
    <Prefer32Bit>false</Prefer32Bit>
  </PropertyGroup>
</Project>
